def print_read_me():
	print 'VaLoR V1.0 12-21-2015'
	print 'Contact: Xuefang Zhao (xuefzhao@umich.edu)'
	print ''
	print 'Usage: VaLoR [Options] [Parameters]'
	print 'Options: '
	print '	svelter'
	print '	vcf'
	print '	bed'
	print 'Parameters:'
	print '	--sv-input:'
	print ' --output-path:'
	print '	--pacbio-input:'
	print '	--reference:'
	print 'Optional Parameters:'
	print '	--window-size'
	print '	--sv-type'
	print ' --size-cff'